name: Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  issueHandler:
    runs-on: windows-latest
    name: Issue Verification
    steps:
      - uses: actions/checkout@main
      - name: Verify Issue
        uses: ScoopInstaller/Scoop-GithubActions@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          USER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
