name: Commented Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Request Validation
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          USER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
